meta_product_name: "TeamTrip"
meta_title: "TeamTrip - Organize your group trip easily"
meta_description: "The group travel app that makes planning trips with friends."
meta_image: "Brainstorming.svg" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
